// assets render: SVG -> PNG via LibreOffice, for deck diagrams generated by
// pitchdeck-build / assets-generator. Degrades gracefully when soffice is absent.
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { okEnvelope, failEnvelope, emit } from '../lib/envelope.js';
import { resolveTool, withPrivateProfile } from '../lib/render.js';

export async function run(args, ctx) {
  const command = 'assets';
  const [sub, ...rest] = args;

  if (sub !== 'render') {
    const msg = `unknown assets subcommand "${sub ?? ''}". Use: render <file.svg> [--out <dir>]`;
    emit(failEnvelope(command, ctx.version, msg), ctx, msg);
    process.stderr.write(msg + '\n');
    return 1;
  }

  const positionals = rest.filter((a) => !a.startsWith('--'));
  const input = positionals[0];
  const outIdx = rest.indexOf('--out');
  const outDir = outIdx >= 0 ? rest[outIdx + 1] : (input ? path.dirname(path.resolve(input)) : null);

  if (!input) {
    const msg = 'assets render requires <file.svg>';
    emit(failEnvelope(command, ctx.version, msg), ctx, msg);
    process.stderr.write(msg + '\n');
    return 1;
  }

  const abs = path.resolve(input);
  if (!fs.existsSync(abs)) {
    const msg = `svg not found: ${abs}`;
    emit(failEnvelope(command, ctx.version, msg), ctx, msg);
    process.stderr.write(msg + '\n');
    return 1;
  }

  const soffice = resolveTool('soffice');
  if (!soffice) {
    const data = { available: false, reason: 'soffice not found (install LibreOffice)', png: null, svg: abs };
    const msg = data.reason;
    emit(okEnvelope(command, ctx.version, data), ctx, msg);
    return 1;
  }

  fs.mkdirSync(outDir, { recursive: true });
  withPrivateProfile((profileArgs) => {
    execFileSync(soffice, [...profileArgs, '--headless', '--convert-to', 'png', '--outdir', outDir, abs], {
      stdio: 'ignore',
      timeout: 120000,
    });
  });

  const png = path.join(outDir, path.basename(abs, '.svg') + '.png');
  if (!fs.existsSync(png)) {
    const msg = `conversion produced no png for ${abs}`;
    emit(failEnvelope(command, ctx.version, msg), ctx, msg);
    process.stderr.write(msg + '\n');
    return 1;
  }

  const data = { available: true, reason: null, png, svg: abs, bytes: fs.statSync(png).size };
  emit(okEnvelope(command, ctx.version, data), ctx, `rendered ${path.basename(png)} (${data.bytes} bytes) → ${png}`);
  return 0;
}
